sources:
  consumer_electronics:
    - name: The Verge
      type: rss
      url: https://www.theverge.com/rss/index.xml
    - name: Android Authority
      type: rss
      url: https://www.androidauthority.com/feed/
    - name: PhoneArena
      type: rss
      url: https://www.phonearena.com/rss/news
channel_news:
  - name: TechCrunch
    type: rss
    url: https://techcrunch.com/feed/

  - name: Business Insider
    type: rss
    url: https://www.businessinsider.com/rss

  - name: CNBC Retail
    type: rss
    url: https://www.cnbc.com/id/10000115/device/rss/rss.html
